const constants = {
  // Reducer Constants
  REQUESTING: 'REQUESTING',
  REQUESTING_SUB_POKE_TYPE: 'REQUESTING_SUB_POKE_TYPE',

  SPELLING_ERROR: 'SPELLING_ERROR',
  SERVER_ERROR: 'SERVER_ERROR',

  ADD_ACTIVE_POKEMON: 'ADD_ACTIVE_POKEMON',
  ADD_ACTIVE_POKE_TYPE: 'ADD_ACTIVE_POKE_TYPE',
  ADD_ACTIVE_SUB_POKE_TYPE: 'ADD_ACTIVE_SUB_POKE_TYPE',

  RECEIVE_POKEMON: 'RECEIVE_POKEMON',
  RECEIVE_POKEMON_DESCRIPTION: 'RECEIVE_POKEMON_DESCRIPTION',
  RECEIVE_POKE_TYPE: 'RECEIVE_POKE_TYPE',

  CLEAR_SUB_POKE_TYPE: 'CLEAR_SUB_POKE_TYPE',

  END_FETCH: 'END_FETCH',

// Traffic Middleware Constants
  FETCH_POKEMON: 'FETCH_POKEMON',
  FETCH_DESCRIPTION: 'FETCH_DESCRIPTION',
  MAIN_TYPE_FETCH: 'MAIN_TYPE_FETCH',
  SUB_TYPE_FETCH: 'SUB_TYPE_FETCH'
}

export default constants
